[package]
name        = "{{project-name}}-core"
description = "Core business logic for {{project-name}}."
version.workspace    = true
edition.workspace    = true
authors.workspace    = true
license.workspace    = true
repository.workspace = true
homepage.workspace   = true

[lints]
workspace = true

[dependencies]
{{project-name}}-types = { path = "../{{project-name}}-types" }
