xflags::xflags! {
    src "./src/flags.rs"

    /// Dev automation for the {{project-name}} workspace.
    cmd xtask {
        /// Check formatting, types, and lints.
        cmd check {}

        /// Run check then the full test suite.
        cmd test {
            /// Optional test filter passed to `cargo test`.
            optional filter: String
        }

        /// Run test then build release artifacts and smoke-test the binary.
        cmd build {}

        /// Scaffold a library crate; the reserved name `cli` adds the project CLI.
        cmd add {
            /// Crate suffix, or `cli` for the uv-style CLI scaffold.
            required name: String
        }

        /// Run `cargo llvm-cov --workspace --html` (requires cargo-llvm-cov).
        cmd coverage {}

        /// Workspace publish via `cargo release`. Dry-run by default.
        cmd publish {
            /// Actually execute the release (default: dry-run).
            optional --execute
            /// Bump level: patch | minor | major.
            optional --level level: String
        }

        /// Regenerate per-crate README.md files (runs scripts/generate-crate-readmes.py).
        cmd readme {}
    }
}

// generated start
// The following code is generated by `xflags` macro.
// Run `env UPDATE_XFLAGS=1 cargo build` to regenerate.
#[derive(Debug)]
pub struct Xtask {
    pub subcommand: XtaskCmd,
}

#[derive(Debug)]
pub enum XtaskCmd {
    Check(Check),
    Test(Test),
    Build(Build),
    Add(Add),
    Coverage(Coverage),
    Publish(Publish),
    Readme(Readme),
}

#[derive(Debug)]
pub struct Check {}

#[derive(Debug)]
pub struct Test {
    pub filter: Option<String>,
}

#[derive(Debug)]
pub struct Build {}

#[derive(Debug)]
pub struct Add {
    pub name: String,
}

#[derive(Debug)]
pub struct Coverage {}

#[derive(Debug)]
pub struct Publish {
    pub execute: bool,
    pub level: Option<String>,
}

#[derive(Debug)]
pub struct Readme {}

#[allow(dead_code)]
impl Xtask {
    pub fn from_env_or_exit() -> Self {
        Self::from_env_or_exit_()
    }
    pub fn from_env() -> xflags::Result<Self> {
        Self::from_env_()
    }
    pub fn from_vec(args: Vec<std::ffi::OsString>) -> xflags::Result<Self> {
        Self::from_vec_(args)
    }
}
// generated end
