use std::fs;
use std::path::{Path, PathBuf};

use toml_edit::{Array, DocumentMut, InlineTable, Item, Value, value};

use crate::Result;
use crate::cli::{CiPreset, ScaffoldCommand};
use crate::workspace::{Workspace, read, read_document};

const GENERATED: &str = "<!-- generated by cargo xtask; rerun the scaffold to update -->";

pub fn run(workspace: &Workspace, command: ScaffoldCommand, dry_run: bool) -> Result {
    match command {
        ScaffoldCommand::Crate { name, bin, private } => {
            add_crate(workspace, &name, bin, private, dry_run)
        }
        ScaffoldCommand::Cli => add_cli(workspace, dry_run),
        ScaffoldCommand::Ci { preset } => add_ci(workspace, preset, dry_run),
        ScaffoldCommand::Docs => add_docs(workspace, dry_run),
        ScaffoldCommand::Agents { claude } => add_agents(workspace, claude, dry_run),
    }
}

pub fn release_files(workspace: &Workspace) -> Result {
    let mut plan = Plan::new(workspace);
    let public_manifest_path = PathBuf::from("crates")
        .join(&workspace.public_crate)
        .join("Cargo.toml");
    let mut public_manifest = read_document(&workspace.path(&public_manifest_path))?;
    let mut hook = Array::new();
    for argument in [
        "cargo",
        "xtask",
        "release",
        "changelog",
        "--tag",
        "{{version}}",
    ] {
        hook.push(argument);
    }
    public_manifest["package"]["metadata"]["release"]["pre-release-hook"] = value(hook);
    plan.replace(public_manifest_path, public_manifest.to_string());
    plan.managed(
        "release.toml",
        "# generated by cargo xtask; rerun `cargo xtask release init` to update\n\
         consolidate-commits = true\n\
         sign-commit = false\n\
         sign-tag = false\n",
        "# generated by cargo xtask",
    )?;
    plan.managed(
        "CHANGELOG.md",
        format!(
            "{GENERATED}\n\n# Changelog\n\n\
             All notable changes will be documented in this file.\n\n\
             <!-- next-header -->\n\n## [Unreleased]\n"
        ),
        GENERATED,
    )?;
    plan.apply(false)
}

fn add_crate(
    workspace: &Workspace,
    suffix: &str,
    binary: bool,
    private: bool,
    dry_run: bool,
) -> Result {
    validate_suffix(suffix)?;
    if suffix == "cli" {
        return Err("`cli` is reserved; run `cargo xtask scaffold cli`".into());
    }

    let crate_name = format!("{}-{suffix}", workspace.public_crate);
    let relative = PathBuf::from("crates").join(&crate_name);
    ensure_new_crate_directory(workspace, &relative)?;
    let mut workspace_manifest = workspace.manifest()?;
    register_workspace_crate(
        &mut workspace_manifest,
        &crate_name,
        &relative,
        &workspace.version,
    )?;

    let mut plan = Plan::new(workspace);
    plan.replace("Cargo.toml", workspace_manifest.to_string());
    plan.create(
        relative.join("Cargo.toml"),
        crate_manifest(&crate_name, binary, private),
    )?;
    let source = if binary {
        format!(
            "//! Executable for `{crate_name}`.\n\nfn main() {{\n    println!(\"Hello from {crate_name}!\");\n}}\n"
        )
    } else {
        format!(
            "//! Library crate `{crate_name}`.\n\n\
             /// Returns a starter message.\n\
             #[must_use]\n\
             pub const fn hello() -> &'static str {{\n\
             \x20   \"Hello from {crate_name}!\"\n\
             }}\n"
        )
    };
    plan.create(
        relative.join(if binary { "src/main.rs" } else { "src/lib.rs" }),
        source,
    )?;
    plan.apply(dry_run)
}

fn add_cli(workspace: &Workspace, dry_run: bool) -> Result {
    let project = &workspace.public_crate;
    let cli_name = format!("{project}-cli");
    let cli_relative = PathBuf::from("crates").join(&cli_name);
    ensure_new_crate_directory(workspace, &cli_relative)?;

    let mut workspace_manifest = workspace.manifest()?;
    register_workspace_crate(
        &mut workspace_manifest,
        &cli_name,
        &cli_relative,
        &workspace.version,
    )?;
    insert_inline_dependency(
        &mut workspace_manifest["workspace"]["dependencies"],
        "clap",
        version_with_features("4", &["derive"]),
    )?;

    let project_manifest_path = PathBuf::from("crates").join(project).join("Cargo.toml");
    let mut project_manifest = read_document(&workspace.path(&project_manifest_path))?;
    project_manifest["package"]["default-run"] = value(project);
    insert_inline_dependency(
        &mut project_manifest["dependencies"],
        &cli_name,
        workspace_reference(),
    )?;
    insert_inline_dependency(
        &mut project_manifest["dependencies"],
        "clap",
        workspace_reference(),
    )?;

    let mut plan = Plan::new(workspace);
    plan.replace("Cargo.toml", workspace_manifest.to_string());
    plan.replace(project_manifest_path, project_manifest.to_string());
    plan.create(
        cli_relative.join("Cargo.toml"),
        cli_manifest(project, &cli_name),
    )?;
    plan.create(cli_relative.join("src/lib.rs"), cli_source(project))?;
    plan.create(
        PathBuf::from("crates")
            .join(project)
            .join("src/bin")
            .join(format!("{project}.rs")),
        binary_source(project),
    )?;
    plan.apply(dry_run)
}

fn add_ci(workspace: &Workspace, preset: CiPreset, dry_run: bool) -> Result {
    let mut plan = Plan::new(workspace);
    let full = matches!(preset, CiPreset::Full);
    plan.managed(
        ".github/workflows/ci.yml",
        if full { CI_FULL } else { CI_LEAN },
        "# generated by cargo xtask",
    )?;
    if full {
        plan.managed("deny.toml", DENY, "# generated by cargo xtask")?;
        plan.managed("typos.toml", TYPOS, "# generated by cargo xtask")?;
        plan.managed(
            ".github/workflows/audit.yml",
            AUDIT,
            "# generated by cargo xtask",
        )?;
        plan.managed(
            ".github/dependabot.yml",
            DEPENDABOT,
            "# generated by cargo xtask",
        )?;
    }
    plan.apply(dry_run)
}

fn add_docs(workspace: &Workspace, dry_run: bool) -> Result {
    let mut plan = Plan::new(workspace);
    plan.managed(
        "CONTRIBUTING.md",
        format!(
            "{GENERATED}\n\n# Contributing\n\n\
             ```sh\ncargo xtask check\ncargo xtask test\ncargo xtask build\n```\n\n\
             Add crates with `cargo xtask scaffold crate <suffix>`.\n"
        ),
        GENERATED,
    )?;
    plan.managed("crates/README.md", &crate_index(workspace)?, GENERATED)?;
    plan.apply(dry_run)
}

fn add_agents(workspace: &Workspace, claude: bool, dry_run: bool) -> Result {
    let mut plan = Plan::new(workspace);
    plan.managed(
        "AGENTS.md",
        format!(
            "{GENERATED}\n\n# Project instructions\n\n\
             - Keep changes focused on the requested behavior.\n\
             - Run `cargo xtask check` after meaningful edits.\n\
             - Run `cargo xtask test` before committing.\n\
             - Add optional project capabilities through `cargo xtask scaffold`.\n"
        ),
        GENERATED,
    )?;
    if claude {
        plan.managed("CLAUDE.md", "@AGENTS.md\n", "@AGENTS.md")?;
    }
    plan.apply(dry_run)
}

fn register_workspace_crate(
    document: &mut DocumentMut,
    crate_name: &str,
    relative: &Path,
    version: &str,
) -> Result {
    let path = relative
        .to_str()
        .ok_or_else(|| format!("non-UTF-8 crate path: {}", relative.display()))?
        .replace('\\', "/");
    insert_inline_dependency(
        &mut document["workspace"]["dependencies"],
        crate_name,
        path_dependency(&path, version),
    )
}

fn insert_inline_dependency(table: &mut Item, name: &str, dependency: InlineTable) -> Result {
    if let Some(existing) = table.get(name) {
        if existing
            .as_inline_table()
            .is_some_and(|existing| inline_tables_match(existing, &dependency))
        {
            return Ok(());
        }
        return Err(format!(
            "workspace dependency {name:?} already has another value"
        ));
    }
    table[name] = Item::Value(Value::InlineTable(dependency));
    Ok(())
}

fn inline_tables_match(left: &InlineTable, right: &InlineTable) -> bool {
    left.len() == right.len()
        && right.iter().all(|(key, value)| {
            left.get(key)
                .is_some_and(|existing| values_match(existing, value))
        })
}

fn values_match(left: &Value, right: &Value) -> bool {
    match (left, right) {
        (Value::String(left), Value::String(right)) => left.value() == right.value(),
        (Value::Boolean(left), Value::Boolean(right)) => left.value() == right.value(),
        (Value::Integer(left), Value::Integer(right)) => left.value() == right.value(),
        (Value::Array(left), Value::Array(right)) => {
            left.len() == right.len()
                && left
                    .iter()
                    .zip(right.iter())
                    .all(|(left, right)| values_match(left, right))
        }
        _ => false,
    }
}

fn path_dependency(path: &str, version: &str) -> InlineTable {
    let mut dependency = InlineTable::new();
    dependency.insert("path", Value::from(path));
    dependency.insert("version", Value::from(version));
    dependency
}

fn workspace_reference() -> InlineTable {
    let mut dependency = InlineTable::new();
    dependency.insert("workspace", Value::from(true));
    dependency
}

fn version_with_features(version: &str, features: &[&str]) -> InlineTable {
    let mut dependency = InlineTable::new();
    dependency.insert("version", Value::from(version));
    let mut values = Array::new();
    values.extend(features.iter().copied());
    dependency.insert("features", Value::Array(values));
    dependency
}

fn validate_suffix(suffix: &str) -> Result {
    let mut chars = suffix.chars();
    let valid = matches!(chars.next(), Some('a'..='z'))
        && chars.all(|character| {
            character.is_ascii_lowercase() || character.is_ascii_digit() || character == '-'
        })
        && !suffix.ends_with('-')
        && !suffix.contains("--");
    if !valid {
        return Err(
            "name must start with a lowercase letter and contain lowercase letters, digits, or single hyphens"
                .into(),
        );
    }
    if suffix == "xtask" {
        return Err("`xtask` is reserved".into());
    }
    Ok(())
}

fn ensure_new_crate_directory(workspace: &Workspace, relative: &Path) -> Result {
    let directory = workspace.path(relative);
    if directory.exists() && !directory.join("Cargo.toml").is_file() {
        return Err(format!(
            "{} already exists without a Cargo.toml; refusing to write into it",
            relative.display()
        ));
    }
    Ok(())
}

fn crate_manifest(name: &str, binary: bool, private: bool) -> String {
    let publish = if private { "publish = false\n" } else { "" };
    let description = if binary { "Executable" } else { "Library" };
    format!(
        "[package]\n\
         name = \"{name}\"\n\
         description = \"{description} crate for {name}.\"\n\
         {publish}\
         version.workspace = true\n\
         edition.workspace = true\n\
         rust-version.workspace = true\n\
         authors.workspace = true\n\
         license.workspace = true\n\
         repository.workspace = true\n\
         homepage.workspace = true\n\n\
         [lints]\nworkspace = true\n"
    )
}

fn cli_manifest(project: &str, cli_name: &str) -> String {
    format!(
        "[package]\n\
         name = \"{cli_name}\"\n\
         description = \"Command-line model for {project}.\"\n\
         publish = false\n\
         version.workspace = true\n\
         edition.workspace = true\n\
         rust-version.workspace = true\n\
         authors.workspace = true\n\
         license.workspace = true\n\
         repository.workspace = true\n\
         homepage.workspace = true\n\n\
         [lints]\nworkspace = true\n\n\
         [dependencies]\nclap = {{ workspace = true }}\n"
    )
}

fn cli_source(project: &str) -> String {
    format!(
        "//! Clap command model for `{project}`.\n\n\
         use clap::{{Parser, Subcommand}};\n\n\
         /// `{project}` command-line interface.\n\
         #[derive(Debug, Parser)]\n\
         #[command(name = \"{project}\", version, about)]\n\
         pub struct Cli {{\n\
         \x20   /// Command to run.\n\
         \x20   #[command(subcommand)]\n\
         \x20   pub command: Command,\n\
         }}\n\n\
         /// Available commands.\n\
         #[derive(Debug, Subcommand)]\n\
         pub enum Command {{\n\
         \x20   /// Print a greeting.\n\
         \x20   Hello {{\n\
         \x20       /// Name to greet.\n\
         \x20       #[arg(default_value = \"world\")]\n\
         \x20       name: String,\n\
         \x20   }},\n\
         }}\n"
    )
}

fn binary_source(project: &str) -> String {
    let crate_name = project.replace('-', "_");
    format!(
        "//! Executable entrypoint for `{project}`.\n\n\
         use clap::Parser;\n\
         use {crate_name}_cli::{{Cli, Command}};\n\n\
         fn main() {{\n\
         \x20   match Cli::parse().command {{\n\
         \x20       Command::Hello {{ name }} => println!(\"Hello, {{name}}!\"),\n\
         \x20   }}\n\
         }}\n"
    )
}

fn crate_index(workspace: &Workspace) -> Result<String> {
    let mut crates = Vec::new();
    for entry in fs::read_dir(workspace.path("crates"))
        .map_err(|error| format!("failed to read crates directory: {error}"))?
    {
        let directory = entry
            .map_err(|error| format!("failed to inspect crates directory: {error}"))?
            .path();
        let manifest_path = directory.join("Cargo.toml");
        if !manifest_path.is_file() {
            continue;
        }
        let manifest = read_document(&manifest_path)?;
        if let Some(name) = manifest["package"]["name"].as_str() {
            crates.push((name.to_owned(), directory));
        }
    }
    crates.sort_by(|left, right| left.0.cmp(&right.0));
    let mut output = format!("{GENERATED}\n\n# Crates\n");
    for (name, directory) in crates {
        let relative = directory
            .strip_prefix(workspace.path("crates"))
            .map_err(|error| format!("failed to make crate path relative: {error}"))?;
        output.push_str(&format!(
            "\n## [{name}](./{})\n",
            relative.to_string_lossy()
        ));
    }
    Ok(output)
}

struct Plan<'a> {
    workspace: &'a Workspace,
    writes: Vec<Write>,
}

struct Write {
    path: PathBuf,
    content: String,
    changed: bool,
}

impl<'a> Plan<'a> {
    fn new(workspace: &'a Workspace) -> Self {
        Self {
            workspace,
            writes: Vec::new(),
        }
    }

    fn create(&mut self, path: impl Into<PathBuf>, content: impl Into<String>) -> Result {
        let path = path.into();
        let content = content.into();
        let absolute = self.workspace.path(&path);
        if absolute.exists() && !absolute.is_file() {
            return Err(format!("{} exists and is not a file", path.display()));
        }
        if absolute.is_file() {
            let existing = read(&absolute)?;
            if existing != content {
                return Err(format!(
                    "{} already exists and is not the generated scaffold",
                    path.display()
                ));
            }
        }
        self.push(path, content);
        Ok(())
    }

    fn managed(
        &mut self,
        path: impl Into<PathBuf>,
        content: impl Into<String>,
        marker: &str,
    ) -> Result {
        let path = path.into();
        if self.workspace.path(&path).is_file()
            && !read(&self.workspace.path(&path))?.starts_with(marker)
        {
            return Err(format!(
                "{} exists without the generated marker; refusing to overwrite it",
                path.display()
            ));
        }
        self.push(path, content.into());
        Ok(())
    }

    fn replace(&mut self, path: impl Into<PathBuf>, content: impl Into<String>) {
        self.push(path.into(), content.into());
    }

    fn push(&mut self, path: PathBuf, content: String) {
        let changed = read(&self.workspace.path(&path)).map_or(true, |current| current != content);
        self.writes.push(Write {
            path,
            content,
            changed,
        });
    }

    fn apply(self, dry_run: bool) -> Result {
        for write in &self.writes {
            println!(
                "{:<9} {}",
                if write.changed { "write" } else { "unchanged" },
                write.path.display()
            );
        }
        if dry_run {
            return Ok(());
        }
        for write in self.writes.into_iter().filter(|write| write.changed) {
            let path = self.workspace.path(&write.path);
            if let Some(parent) = path.parent() {
                fs::create_dir_all(parent)
                    .map_err(|error| format!("failed to create {}: {error}", parent.display()))?;
            }
            fs::write(&path, write.content)
                .map_err(|error| format!("failed to write {}: {error}", path.display()))?;
        }
        Ok(())
    }
}

const CI_LEAN: &str = r#"# generated by cargo xtask; rerun `cargo xtask scaffold ci` to update
name: CI

on:
  push:
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: moonrepo/setup-rust@v1
        with:
          inherit-toolchain: true
          components: clippy,rustfmt
      - run: cargo xtask ci
"#;

const CI_FULL: &str = r#"# generated by cargo xtask; rerun `cargo xtask scaffold ci --preset full` to update
name: CI

on:
  push:
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: moonrepo/setup-rust@v1
        with:
          inherit-toolchain: true
          components: clippy,rustfmt
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-deny@0.20.2,typos-cli@1.48.0
      - run: cargo xtask ci --full
"#;

const DENY: &str = r#"# generated by cargo xtask; rerun `cargo xtask scaffold ci --preset full` to update
[graph]
all-features = true

[advisories]
version = 2
yanked = "warn"

[bans]
multiple-versions = "warn"
wildcards = "deny"

[licenses]
version = 2
allow = ["MIT", "Apache-2.0", "Apache-2.0 WITH LLVM-exception", "BSD-2-Clause", "BSD-3-Clause", "ISC", "Unicode-3.0", "Zlib", "CC0-1.0"]
unused-allowed-license = "allow"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
"#;

const TYPOS: &str = r#"# generated by cargo xtask; rerun `cargo xtask scaffold ci --preset full` to update
[default.extend-words]
clippy = "clippy"

[files]
extend-exclude = ["CHANGELOG.md", "Cargo.lock", "*.snap"]
"#;

const AUDIT: &str = r#"# generated by cargo xtask; rerun `cargo xtask scaffold ci --preset full` to update
name: Audit

on:
  schedule:
    - cron: "0 6 * * *"
  push:
    paths: ["**/Cargo.toml", "**/Cargo.lock"]
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rustsec/audit-check@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
"#;

const DEPENDABOT: &str = r#"# generated by cargo xtask; rerun `cargo xtask scaffold ci --preset full` to update
version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
"#;
