[package]
name        = "{{project-name}}-cli"
description = "Command-line interface for {{project-name}}."
version.workspace    = true
edition.workspace    = true
authors.workspace    = true
license.workspace    = true
repository.workspace = true
homepage.workspace   = true

[lints]
workspace = true

[[bin]]
name = "{{project-name}}"
path = "src/main.rs"

[dependencies]
{{project-name}} = { path = "../{{project-name}}" }
