[package]
name        = "{{project-name}}-cli"
description = "Command-line interface for {{project-name}}."
publish     = false
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
authors.workspace      = true
license.workspace      = true
repository.workspace   = true
homepage.workspace     = true

[lints]
workspace = true

[[bin]]
name = "{{project-name}}"
path = "src/main.rs"

[dependencies]
{{project-name}}   = { workspace = true }
anyhow             = { workspace = true }
clap               = { workspace = true }
tracing            = { workspace = true }
tracing-subscriber = { workspace = true }
