name: CI

on:
  push:
    branches:
      - main
      - "dev/**"
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: short

jobs:
  template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: moonrepo/setup-rust@v1
        with:
          inherit-toolchain: true
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-generate
      - uses: astral-sh/setup-uv@v7
      - run: bash scripts/test-template.sh
